### ISSUE TITLE
Tutilinio lapo pakoregavimas

### ISSUE THREAD

**Issue by JMaciulis** [LIKS/bachelor_thesis_template_vu_mif_cs1#2]
Laba,
norėjau pasidalint pastebėjimu visuose MIF šablonuose yra menka klaida. Keitėsi mifo struktūra, po fakultetu atsirado naujas org. vienetas "Informatikos institutas". To šiuo metu nėra tituliniam.

**Comment by niekas** [comment]
Papildžiau titulinį pridėdamas "Informatikos institutas".
